export const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY";
export const SET_CATEGORY_IMAGES = "SET_CATEGORY_IMAGES";
export const SET_LIMIT = "SET_LIMIT";
export const RESET_SET_LIMIT = "RESET_SET_LIMIT";
